name: Increment Semantic Version - With Build Numbers
description: Bump a given semantic version by a release type ( major | minor | patch ), add a possible postfix ( alpha | beta | rc ) pt
author: Fork by Tuomas Liinamaa, original by Christian Dräger
branding:
  icon: 'tag'
  color: 'purple'
inputs:
  current-version:
    description: 'The current semantic version you want to increment'
    required: true
  version-fragment:
    description: 'The versions fragment you want to increment. possible options are [ major | feature | bug | alpha | beta | rc | build ]'
    required: true
  include-build-number:
    description: 'If you want to always include a build number (ie. every version increase would include a build number of 1, e.g. 1.0.0+build.1)'
    required: false
    default: "false"
outputs:
  next-version:
    description: 'The incremented version'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.current-version }}
    - ${{ inputs.version-fragment }}
    - ${{ inputs.include-build-number }}
